name: "Nix Build and Test"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v11
      - uses: DeterminateSystems/magic-nix-cache-action@v7
      - name: Run Flake Check (includes formatting)
        run: nix flake check

  lint-and-analyze:
    runs-on: ubuntu-latest
    needs: [check-and-format]
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v11
      - uses: DeterminateSystems/magic-nix-cache-action@v7

      - name: Check for nix formatting
        run: nix fmt -- --fail-on-change .
