name: "Nix Build and Test"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checks:
    name: Check ${{ matrix.check }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        check:
          - e2e-local
          - e2e-remote-local
          - e2e-remote-slurm
          - fast-checks
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v11
      - uses: DeterminateSystems/magic-nix-cache-action@v7

      - name: Run Fast Checks and Build
        if: matrix.check == 'fast-checks'
        run: |
          nix build -L \
            .#checks.x86_64-linux.deadnix \
            .#checks.x86_64-linux.statix \
            .#checks.x86_64-linux.formatting \
            .#checks.x86_64-linux.shebang \
            .#checks.x86_64-linux.shellcheck \
            .#packages.x86_64-linux.default

      - name: Run E2E Check
        if: matrix.check != 'fast-checks'
        run: nix build -L .#checks.x86_64-linux.${{ matrix.check }}
