name: "Nix Build and Test"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  fast-checks:
    name: Fast Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v11
      - uses: DeterminateSystems/magic-nix-cache-action@v7

      - name: Run Fast Checks
        run: |
          nix build -L \
            .#checks.x86_64-linux.deadnix \
            .#checks.x86_64-linux.statix \
            .#checks.x86_64-linux.formatting \
            .#checks.x86_64-linux.shebang \
            .#checks.x86_64-linux.shellcheck

  checks:
    name: Check ${{ matrix.check }}
    needs: fast-checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        check:
          - e2e-local
          - e2e-remote-local
          - e2e-remote-slurm
          - static-analysis
          - foreign-distro-compat
          - e2e-impure
          - e2e-mount-paths
          - e2e-impure-podman
          - e2e-mount-paths-podman
          - e2e-impure-docker
          - e2e-mount-paths-docker
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v11
      - uses: DeterminateSystems/magic-nix-cache-action@v7

      - name: Run E2E Check
        run: nix build -L .#checks.x86_64-linux.${{ matrix.check }}
